---
apiVersion: v1
kind: Service
metadata:
  name: my-goweb-service
spec:
  type: LoadBalancer
  ports:
  - name: tcp
    port: 7000
    targetPort: 4000
    nodePort: 31555
  selector:
    name: my-goweb-app
