---
- name: Create pods using deployment 
  hosts: 34.201.52.21 
  become: true
  #user: ec2-user
 
  tasks: 
  - name: create a deployment
    command: kubectl apply -f /home/ec2-user/gowebapp-deployment.yaml
 
