---
- name: create service for deployment
  hosts: 34.201.52.21
  become: true
  #user: ec2-user

  tasks:
  - name: create a service
    command: kubectl apply -f /home/ec2-user/gowebapp-service.yaml
